### ISSUE TITLE
Request to change the theme icon

### ISSUE THREAD

**Issue by mgmeyers** [Hamza-Aziane/obsidian-dark#1]
Hi there,

It seems you're using obsidian's icon (see https://obsidian.md/) as your own: 

https://github.com/Hamza-Aziane/obsidian-dark/blob/87013417b51cf0e5654258d358ebb8afcb3f2d93/icon.png

Do you have permission to use the icon in this way? I believe it is copyrighted.

**Comment by ericaxu** [comment]
Hi, creator of Obsidian here and would like you to change to another icon.

Doesn't seem like your theme has anything to do with the Obsidian app but rather only features the purple color (I'm trying to guess if that's why it's called Obsidian), so it would be good if you can use another icon to not give the wrong impression.

Thank you for considering!

**Comment by Hamza-Aziane** [comment]
@ericaxu , @mgmeyers Thank you guys for reaching out to me about this issue.

"Doesn't seem like your theme has anything to do with the Obsidian app" Exactly, in matter fact I haven't even heard of this app, I didn't know that the Icon is copyrighted as I've been searching for a good looking obsidian icon (the volcanic glass). The name obsidian was choisen bcz of the dark color scheme I'm using in this theme, another inspiration for this name is the obsidian fury mecha from the movie Pacific Rim.

The icon will be changed in the next update. Thanks for letting me it's a copyrighted material.

**Comment by Hamza-Aziane** [comment]
@ericaxu The icon has been changed, you can check it at https://github.com/Hamza-Aziane/obsidian-dark/blob/main/icon.png

Please let me know if there's anything else, before closing this issue.

I've just checked obsidian.md on Youtube, great project you guys have made, I might give it a try in my free time and see how it goes.
